# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AUTHOR_NAME: 'AmbaNum Bot'
  AUTHOR_EMAIL: 'ambanum.bot@disinfo.quaidorsay.fr'

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.17'
    - run: npm ci
    - run: npm test
